[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-cors = "0.7.0"
actix-web = "4.9.0"
env_logger = "0.11.6"
log = "0.4.22"
shared = { version = "0.1.0", path = "../shared" }
