[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[dependencies]
egui = { version = "0.30.0", features = ["serde"] }
env_logger = "0.11.6"
log = "0.4.22"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.137"
